### ISSUE TITLE
PIOT-GDA-09-003: Add Discovery functionality to CoapClientConnector

### ISSUE THREAD

**Issue by labbenchstudios** [programming-the-iot/book-exercise-tasks#107]
**Description**

- Add discovery functionality to the recently created `CoapClientConnector` class.
  - NOTE: These instructions make use of one or both of the following CoAP libraries:
    - The californium-core open source CoAP library, located at: [californium-core](https://github.com/eclipse/californium). Reference: Eclipse Foundation, Inc. californium. (2020) [Online]. Available. https://github.com/eclipse/californium.
    - The californium-core/scandium open source CoAP library, located at: [californium/scandium-core](https://github.com/eclipse/californium/tree/master/scandium-core). Reference: Eclipse Foundation, Inc. scandium-core. (2021) [Online]. Available. https://github.com/eclipse/californium/tree/master/scandium-core.

***Review the README***
- Please see [README.md](https://github.com/programming-the-iot/book-exercise-tasks) for further information on, and use of, this content.
- License for embedded documentation and source codes: [PIOT-DOC-LIC](https://github.com/programming-the-iot/book-exercise-tasks/issues/165)

***Estimated effort may vary greatly***
- The estimated level of effort for this exercise shown in the 'Estimate' section below is a very rough approximation. The actual level of effort may vary greatly depending on your development and test environment, experience with the requisite technologies, and many other factors.

**Actions**

- Implement the `sendDiscoveryRequest()` method. This will issue a discovery request to the server, which will provide a list of resource names (fully qualified) that are currently registered with the server.

NOTE: There are three ways to implement a Discovery request:

- Option 1: Use the client discovery API (synchronous):
```java
Set<WebLink> wlSet = this.clientConn.discover();

if (wlSet != null) {
    for (WebLink wl : wlSet) {
        _Logger.info(" --> URI: " + wl.getURI() + ". Attributes: " + wl.getAttributes());
    }
}
```

- Option 2: Send a special GET to the server (synchronous):
```java
this.clientConn.setURI("/.well-known/core");

CoapResponse response = this.clientConn.get();

String[] resources = response.getResponseText().split(",");

for (String resource : resources) {
	_Logger.info("--> URI: " + resource.replace("<", "").replace(">",  ""));
}
```

- Option 3: Send a special GET to the server (asynchronous with callback)
  - NOTE: If you test this approach, you'll likely need to issue the request, then implement your own sleep in the main thread to wait for a response to be processed. I've tested this with a 2-second delay when running the server and client within my local environment.
```java
this.clientConn.setURI("/.well-known/core");

// TODO: implement your own Discovery-specific response handler if you'd like, using the parsing logic from Option 2
GenericCoapResponseHandler responseHander = new GenericCoapResponseHandler(this.dataMsgListener);
this.clientConn.get(responseHandler);
```
**Estimate**

- Small

**Tests**

- Setup
  - Start your GDA application with the CoAP server enabled. Make sure it runs for a couple of minutes - long enough for you to run the integration tests listed below.
    - To run your GDA from the command line, you just need to do the following from a shell starting from the GDA_HOME directory (e.g., where you cloned gda-java-components). For this test, the assumption is that you named your directory 'piot-java-components':
      - NOTE: Be sure to run your GDA Java app for a few minutes so you have time to run the tests!!
```java
cd piot-java-components
mvn install -DskipTests
java -jar target/gateway-device-app-0.0.1-jar-with-dependencies.jar
```
- Update, then run, the `CoapClientConnectorTest` in ./src/test/java/programmingtheiot/integration/connection as a JUnit test case.
  - If not already created, add a new test case method named `testConnectAndDiscover()` to the class to handle discovery. It should look similar to the following:
```java
@Test
public void testConnectAndDiscover()
{
	assertTrue(this.coapClient.sendDiscoveryRequest(DEFAULT_TIMEOUT));

	// NOTE: If you are using a custom asynchronous discovery, include a brief wait here
	try {
		Thread.sleep(2000L);
	} catch (InterruptedException e) {
		// ignore
	}
}
```
  - Execute the `CoapClientConnectorTest` test cases named `testConnectAndDiscover()`. It should generate some log output on both the client and the server. For the client, the output should look similar to the following (depending on your implementation of course:
```
.
.
.
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector initClient
INFO: Created client connection to server / resource: coap://localhost:5683
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector <init>
INFO: Using URL for server conn: coap://localhost:5683
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO: Issuing discover...
Nov 10, 2020 10:57:08 AM org.eclipse.californium.core.network.CoapEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:0
Nov 10, 2020 10:57:08 AM org.eclipse.californium.core.network.EndpointManager createDefaultEndpoint
INFO: Created implicit default endpoint 0.0.0.0/0.0.0.0:55177
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /.well-known/core. Attributes: org.eclipse.californium.core.server.resources.ResourceAttributes@453da22c
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT. Attributes: org.eclipse.californium.core.server.resources.ResourceAttributes@71248c21
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/ConstrainedDevice. Attributes: org.eclipse.californium.core.server.resources.ResourceAttributes@44
2675e1
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/ConstrainedDevice/ActuatorCmd. Attributes: org.eclipse.californium.core.server.resources.ResourceA
ttributes@6166e06f
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/ConstrainedDevice/ActuatorResponse. Attributes: org.eclipse.californium.core.server.resources.Reso
urceAttributes@49e202ad
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/ConstrainedDevice/MgmtStatusCmd. Attributes: org.eclipse.californium.core.server.resources.Resourc
eAttributes@1c72da34
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/ConstrainedDevice/MgmtStatusMsg. Attributes: org.eclipse.californium.core.server.resources.Resourc
eAttributes@6b0c2d26
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/ConstrainedDevice/SensorMsg. Attributes: org.eclipse.californium.core.server.resources.ResourceAtt
ributes@3d3fcdb0
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/ConstrainedDevice/SystemPerfMsg. Attributes: org.eclipse.californium.core.server.resources.Resourc
eAttributes@641147d0
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/GatewayDevice. Attributes: org.eclipse.californium.core.server.resources.ResourceAttributes@6e3892
1c
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/GatewayDevice/MgmtStatusCmd. Attributes: org.eclipse.californium.core.server.resources.ResourceAtt
ributes@64d7f7e0
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/GatewayDevice/MgmtStatusMsg. Attributes: org.eclipse.californium.core.server.resources.ResourceAtt
ributes@27c6e487
Nov 10, 2020 10:57:08 AM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO:  --> URI: /PIOT/GatewayDevice/SystemPerfMsg. Attributes: org.eclipse.californium.core.server.resources.ResourceAtt
ributes@49070868
Nov 10, 2020 10:57:08 AM org.eclipse.californium.core.CoapServer stop
INFO: Stopping server
Nov 10, 2020 10:57:08 AM org.eclipse.californium.core.network.CoapEndpoint stop
INFO: Stopping endpoint at address 0.0.0.0/0.0.0.0:5683
```

**Comment by BenderPL0120** [comment]
```
	private void initClient()
	{
		try {
			this.clientConn = new CoapClient(this.serverAddr);
			_Logger.info("Created client connection to server / resource: " + this.serverAddr);
		} catch (Exception e) {
			_Logger.log(Level.SEVERE, "Failed to connect to broker: " + (this.clientConn != null ? this.clientConn.getURI() : this.serverAddr), e);
		}
	}
```

When using the method described in 09-001 for initialization, the following error occurs during testing:
```
INFO: Using URL for server conn: coap://localhost:5683
Oct 30, 2025 5:20:33 PM programmingtheiot.gda.connection.CoapClientConnector sendDiscoveryRequest
INFO: Issuing discovery request to server (timeout: 5s)...

java.lang.IllegalStateException: Configuration contains no definitions!

    at org.eclipse.californium.elements.config.Configuration.add(Configuration.java:802)
    at org.eclipse.californium.elements.config.Configuration.load(Configuration.java:772)
```


The problem is Californium library (version 3.x) requires configuration definitions to be properly initialized, we need to initialize the Californium configuration inside `initClient()` method. Here is a solution:

```

// Add these imports at the top of CoapClientConnector.java file:
import org.eclipse.californium.core.config.CoapConfig;
import org.eclipse.californium.elements.config.Configuration;
import org.eclipse.californium.elements.config.UdpConfig;

// Replace existing initClient() method with this:
private void initClient()
{
    try {
        // Initialize Californium configuration with required definitions
        Configuration.setStandard(new Configuration(CoapConfig.DEFINITIONS, UdpConfig.DEFINITIONS));
        
        // Now create the CoAP client
        this.clientConn = new CoapClient(this.serverAddr);
        
        _Logger.info("Created client connection to server / resource: " + this.serverAddr);
    } catch (Exception e) {
        _Logger.log(Level.SEVERE, "Failed to connect to broker: " + 
            (this.clientConn != null ? this.clientConn.getURI() : this.serverAddr), e);
    }
}

**Comment by labbenchstudios** [comment]
Thanks for the find, BlenderPL0120. Will run some tests to verify and update the instructions accordingly.

**Comment by labbenchstudios** [comment]
PIOT-GDA-09-001 has been updated: https://github.com/programming-the-iot/book-exercise-tasks/issues/99. Appreciate the find!
