### ISSUE TITLE
PIOT-CDA-03-001: Create / update data containers for data collection and actuation

### ISSUE THREAD

**Issue by labbenchstudios** [programming-the-iot/book-exercise-tasks#57]
**Description**

- Create (or edit the exiting) Python modules that will contain the sensor and actuator data, as well as the base class (BaseIotData) they'll all sub-class: SensorData, ActuatorData, and SystemPerformanceData. These will all be derived from BaseIotData, and will have very simple implementations.

NOTE 1: The shells of each module are part of the python-components repo. If you'd prefer, you may create your own instead.

NOTE 2: These classes will all have corresponding implementations in the GDA code base so as to allow for programmatic access to the data and functionality across both applications. Don't worry about the GDA work now - we'll tackle that in Chapter 5.

***Review the README***
- Please see [README.md](https://github.com/programming-the-iot/book-exercise-tasks) for further information on, and use of, this content.
- License for embedded documentation and source codes: [PIOT-DOC-LIC](https://github.com/programming-the-iot/book-exercise-tasks/issues/165)

***Estimated effort may vary greatly***
- The estimated level of effort for this exercise shown in the 'Estimate' section below is a very rough approximation. The actual level of effort may vary greatly depending on your development and test environment, experience with the requisite technologies, and many other factors.

**Actions**

IMPORTANT NOTE 1: As mentioned in [Chapter 1 of Programming the IoT](https://learning.oreilly.com/library/view/programming-the-internet/9781492081401/ch01.html) within the **_Application configuration_** section, I suggest setting the ```DEFAULT_CONFIG_FILE_NAME``` property in ```ConfigConst.py``` to the absolute path for PiotConfig.props. This will enable both the test classes and the application to find the configuration file, as the relative path will be different for each due to the delta between the ./src/main/python and ./src/test/python directory hierarchy levels.

IMPORTANT NOTE 2: While the implementation examples depicted here are only one way to implement the requirements listed, it's very important to ensure the variable and type names remain consistent between the CDA data container implementations (shown here) and the GDA data container implementations (shown in [Lab Module 05](https://github.com/orgs/programming-the-iot/projects/1#column-10488421)). This will allow your integration tests to succeed now and in the future when serializing / de-serializing your data containers to / from JSON and between the CDA and GDA.

- Review [BaseIotData](https://github.com/programming-the-iot/python-components/blob/default/programmingtheiot/data/BaseIotData.py), located in the [python-components](https://github.com/programming-the-iot/python-components/) repository.
  - This base class serves as the foundation for all data containers in the CDA.
    - Constructor: Notice that it accepts two parameters - the name and the type ID. Both will be passed in by the sub-class during initialization, although they can be set later via the accessor methods.
    - Accessor Methods: Notice there are a number of accessor methods representing shared properties, including name, type ID, status code and time stamp. The other modules referenced here will contain classes that derive from `BaseIotData`.
  - NOTE: You're welcome to create your own abstraction infrastructure; however, all of the exercises will expect the properties described in `BaseIotData` to exist.

***ActuatorData***
- Create (edit) `ActuatorData` (a shell for this already exists in python-components)
  - This represents a simple actuator data command with support for float values and string-based state data (useful for sending a text message to an LED display, for instance).
  - Create a constructor that accepts two parameters: `name` and `typeID`.
    - Pass the name and typeID to the base class constructor.
    - Set a class-scoped variable called `value`, with a default of `ConfigConst.DEFAULT_VAL`
    - Set a class-scoped variable called `command`, with a  default of `ConfigConst.DEFAULT_COMMAND`
    - Set a class-scoped variable called `stateData`, with a default of ""
  - As with `SensorData`, add getter and setter accessor methods for `self.value`
  - Add getter and setter methods for `self.command`
    - The setter for `self.command` can also invoke `self.updateTimeStamp()`, although that's optional, since actuator messages are less likely to be re-used, since they typically represent a one-off event
  - Add getter and setter methods for `self.stateData`
  - Add a private method called `_handleUpdateData(self, data)`, where `data` is a `ActuatorData` instance, and sets the `self.value`, `self.command`, and `self.stateData` to that contained within `data`. It doesn't need to set the time stamp, but it should handle any exceptions, if - for instance - the `data` type is not `ActuatorData`. This call will be invoked by the base class.
  - Optional: Add a `__str__(self)` implementation that will return a stringified representation of `ActuatorData` when called.
  - Shown below is one example for implementing the constructor and accessor methods of `ActuatorData`:
```python
def __init__(self, typeID: int = ConfigConst.DEFAULT_ACTUATOR_TYPE, name = ConfigConst.NOT_SET, d = None):
	super(ActuatorData, self).__init__(name = name, typeID = typeID, d = d)
	
	self.value = ConfigConst.DEFAULT_VAL
	self.command = ConfigConst.DEFAULT_COMMAND
	self.stateData = ""
	self.isResponse = False

def getCommand(self) -> int:
	return self.command

def getStateData(self) -> str:
	return self.stateData

def getValue(self) -> float:
	return self.value

def isResponseFlagEnabled(self) -> bool:
	return self.isResponse

def setCommand(self, command: int):
	self.command = command
	self.updateTimeStamp()

def setAsResponse(self):
	self.isResponse = True
	self.updateTimeStamp()
	
def setStateData(self, stateData: str):
	if stateData:
		self.stateData = stateData
		self.updateTimeStamp()

def setValue(self, val: float):
	self.value = val
	self.updateTimeStamp()
	
def _handleUpdateData(self, data):
	if data and isinstance(data, ActuatorData):
		self.command = data.getCommand()
		self.stateData = data.getStateData()
		self.value = data.getValue()
		self.isResponse = data.isResponseFlagEnabled()
```

***SensorData***
- Create (edit) `SensorData` (a shell for this already exists in python-components)
  - This represents simple sensor data with support for float values (only - as that's all we'll need for these exercises), and derives from `BaseIotData`.
  - Create a constructor that accepts two parameters: `name` and `typeID`.
    - Pass the name and typeID to the base class constructor.
    - Set a class-scoped variable called 'value', with a default of `ConfigConst.DEFAULT_VAL`
  - Add a getter accessor method for `self.value`
  - Add a setter accessor method for `self.value` that accepts a new value as the parameter, sets the class-scoped `self.value` to the parameter, and also updates the time stamp by invoking the base class `self.updateTimeStamp()`
    - The reason for updating the timestamp here is in case the object is re-used with a new value set well after initialization to ensure the time stamp aligns to the time the value was set.
  - Add a private method called `_handleUpdateData(self, data)`, where `data` is a `SensorData` instance, and sets the `self.value` to that contained within `data`. It doesn't need to set the time stamp, but it should handle any exceptions, if - for instance - the `data` type is not `SensorData`. This call will be invoked by the base class.
  - Optional: Add a `__str__(self)` implementation that will return a stringified representation of `SensorData` when called.
  - Shown below is an example of one way to implement `SensorData`:
```python
def __init__(self, typeID: int = ConfigConst.DEFAULT_SENSOR_TYPE, name = ConfigConst.NOT_SET, d = None):
	super(SensorData, self).__init__(name = name, typeID = typeID, d = d)
	
	self.value = ConfigConst.DEFAULT_VAL
	
def getValue(self) -> float:
	return self.value
	
def setValue(self, newVal: float):
	self.value = newVal
	self.updateTimeStamp()
		
def _handleUpdateData(self, data):
	if data and isinstance(data, SensorData):
		self.value = data.getValue()
```

***SystemPerformanceData***
- Create (edit) `SystemPerformanceData` (a shell for this already exists in python-components)
  - This module and its class follow a similar pattern as the previous, except that it has (for now) two data values: CPU utilization and memory utilization. You can add more if you'd like, of course, but these are the values needed for the remaining exercises.
  - Create a no-arg constructor that will pass `ConfigConst.SYS_PERF_NAME` as the name, and `ConfigConst.SYS_PERF_TYPE` as the typeID
    - Set a class-scoped variable called `cpuUtil`, with a default of `ConfigConst.DEFAULT_VAL`
    - Set a class-scoped variable called `memUtil`, with a default of `ConfigConst.DEFAULT_VAL`
  - Add getter and setter methods for `self.cpuUtil` - be sure to update the time stamp when called
  - Add getter and setter methods for `self.memUtil` - be sure to update the time stamp when called
  - Add a private method called `_handleUpdateData(self, data)`, where `data` is a `SystemPerformanceData` instance, and sets the `self.cpuUtil`, `self.memUtil`, and `self.diskUtil` variables to that contained within `data`. It doesn't need to set the time stamp, but it should handle any exceptions, if - for instance - the `data` type is not `SystemPerformanceData`. This call will be invoked by the base class.
  - Optional: Add a `__str__(self)` implementation that will return a stringified representation of `SytemPerformanceData` when called.
  - Shown below is an example of one way to implement `SystemPerformanceData`:
```python
def __init__(self, d = None):
	super(SystemPerformanceData, self).__init__(name = ConfigConst.SYSTEM_PERF_MSG, typeID = ConfigConst.SYSTEM_PERF_TYPE, d = d)
	
	self.cpuUtil = ConfigConst.DEFAULT_VAL
	self.memUtil = ConfigConst.DEFAULT_VAL
	
def getCpuUtilization(self):
	return self.cpuUtil
	
def getMemoryUtilization(self):
	return self.memUtil
	
def setCpuUtilization(self, cpuUtil):
	self.cpuUtil = cpuUtil
	self.updateTimeStamp()
	
def setMemoryUtilization(self, memUtil):
	self.memUtil = memUtil
	self.updateTimeStamp()
	
def _handleUpdateData(self, data):
	if data and isinstance(data, SystemPerformanceData):
		self.cpuUtil = data.getCpuUtilization()
		self.memUtil = data.getMemoryUtilization()
```

NOTE: There are a limited number of 'consts' representing sensor and actuator types within the `ConfigConst` class (using a simple integer value scheme). You can add more if you'd like or expand upon the convention and create an `Enum` to represent the different types you might encounter. Further, you could use a string instead, although it makes some validation more challenging.

**Estimate**

- Medium

**Tests**

- Unit tests (in CDA_HOME/tests/unit/data)
  - The following unit tests should all pass (NOTE: The `.py` Python extension is implied)
    - `test_ActuatorData`
    - `test_SensorData`
    - `test_SystemPerformanceData`

**Comment by MAbuShattal** [comment]
I'm testing SensorDataTest.py and worked fine. The result is as shown below:
```
2021-12-13 01:22:23,278:SensorDataTest:INFO:Testing SensorData class...
2021-12-13 01:22:23,284:ConfigUtil:INFO:Loading config: ../../../../../../../config/PiotConfig.props
2021-12-13 01:22:23,285:ConfigUtil:DEBUG:Config: ['Mqtt.GatewayService', 'Coap.GatewayService', 'ConstrainedDevice']
2021-12-13 01:22:23,285:ConfigUtil:INFO:Created instance of ConfigUtil: <programmingtheiot.common.ConfigUtil.ConfigUtil object at 0x7ff7a03b5ee0>
2021-12-13 01:22:23,285:SensorDataTest:INFO:Sensor data as string: name=Not Set,typeID=0,timeStamp=2021-12-13T06:22:23.278532+00:00,statusCode=0,hasError=False,locationID=constraineddevice001,elevation=0.0,latitude=0.0,longitude=0.0
2021-12-13 01:22:23,285:SensorDataTest:INFO:Sensor data as string: name=SensorDataFooBar,typeID=0,timeStamp=2021-12-13T06:22:23.285962+00:00,statusCode=0,hasError=False,locationID=constraineddevice001,elevation=0.0,latitude=0.0,longitude=0.0
2021-12-13 01:22:23,287:SensorDataTest:INFO:Sensor data as string: name=SensorDataFooBar,typeID=0,timeStamp=2021-12-13T06:22:23.287683+00:00,statusCode=0,hasError=False,locationID=constraineddevice001,elevation=0.0,latitude=0.0,longitude=0.0
----------------------------------------------------------------------
Ran 3 tests in 0.011s

OK
```

I mimicked the same functionality from SensorData.py and SensorDataTest.py to implement ActuatorDataTest.py. One thing I noticed is that there is a discrepancy between the instruction in the repository and the book:

- In the website action list: 		self.stateData = ""

- In the book code listing: 		self.stateData = None

Testing ActuatorDataTest.py and would run into this error:
```
Finding files... done.
Importing test modules ... done.

2021-12-14 11:01:26,466:ActuatorDataTest:INFO:Testing ActuatorData class...
2021-12-14 11:01:26,471:ConfigUtil:INFO:Loading config: ../../../../../../../config/PiotConfig.props
2021-12-14 11:01:26,472:ConfigUtil:DEBUG:Config: ['Mqtt.GatewayService', 'Coap.GatewayService', 'ConstrainedDevice']
2021-12-14 11:01:26,472:ConfigUtil:INFO:Created instance of ConfigUtil: <programmingtheiot.common.ConfigUtil.ConfigUtil object at 0x7fd3a8f67d30>
2021-12-14 11:01:26,474:ActuatorDataTest:INFO:Actuator data as string: name=ActuatorDataFooBar,typeID=0,timeStamp=2021-12-14T16:01:26.474564+00:00,statusCode=0,hasError=False,locationID=constraineddevice001,elevation=0.0,latitude=0.0,longitude=0.0
2021-12-14 11:01:26,475:ActuatorDataTest:INFO:Actuator data as string: name=ActuatorDataFooBar,typeID=0,timeStamp=2021-12-14T16:01:26.475699+00:00,statusCode=0,hasError=False,locationID=constraineddevice001,elevation=0.0,latitude=0.0,longitude=0.0
======================================================================
FAIL: testDefaultValues (src.test.python.programmingtheiot.part02.unit.data.ActuatorDataTest.ActuatorDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mas/programmingtheiot/python-components/src/test/python/programmingtheiot/part02/unit/data/ActuatorDataTest.py", line 45, in testDefaultValues
    self.assertEquals(ad.getCommand(), ConfigConst.DEFAULT_COMMAND)
AssertionError: None != 0

======================================================================
FAIL: testFullUpdate (src.test.python.programmingtheiot.part02.unit.data.ActuatorDataTest.ActuatorDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mas/programmingtheiot/python-components/src/test/python/programmingtheiot/part02/unit/data/ActuatorDataTest.py", line 64, in testFullUpdate
    self.assertEquals(ad.getCommand(), ConfigConst.COMMAND_ON)
AssertionError: None != 1

======================================================================
FAIL: testParameterUpdates (src.test.python.programmingtheiot.part02.unit.data.ActuatorDataTest.ActuatorDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mas/programmingtheiot/python-components/src/test/python/programmingtheiot/part02/unit/data/ActuatorDataTest.py", line 54, in testParameterUpdates
    self.assertEquals(ad.getCommand(), ConfigConst.COMMAND_ON)
AssertionError: None != 1

----------------------------------------------------------------------
Ran 3 tests in 0.012s

FAILED (failures=3)

```



Below is the code for ActuatorDataTest.py: 
```
#####
# 
# This class is part of the Programming the Internet of Things
# project, and is available via the MIT License, which can be
# found in the LICENSE file at the top level of this repository.
# 
# Copyright (c) 2020 by Andrew D. King
# 

import logging
import unittest

import programmingtheiot.common.ConfigConst as ConfigConst

from programmingtheiot.data.ActuatorData import ActuatorData


class ActuatorDataTest(unittest.TestCase):
	"""
	This test case class contains very basic unit tests for
	ActuatorData. It should not be considered complete,
	but serve as a starting point for the student implementing
	additional functionality within their Programming the IoT
	environment.
	"""
	
	DEFAULT_NAME = "ActuatorDataFooBar"
	DEFAULT_STATE_DATA = "{state: None}"
	DEFAULT_VALUE = 15.2
	
	@classmethod
	def setUpClass(self):
		logging.basicConfig(format='%(asctime)s:%(module)s:%(levelname)s:%(message)s', level=logging.DEBUG)
		logging.info("Testing ActuatorData class...")
		
	def setUp(self):
		pass

	def tearDown(self):
		pass
	
	def testDefaultValues(self):
		ad = ActuatorData()
		
		self.assertEquals(ad.getCommand(), ConfigConst.DEFAULT_COMMAND)
		self.assertEquals(ad.getStatusCode(), ConfigConst.DEFAULT_STATUS)
		
		logging.info("Actuator data as string: " + str(ad))

	def testParameterUpdates(self):
		ad = self._createTestActuatorData()
		
		self.assertEquals(ad.getName(), self.DEFAULT_NAME)
		self.assertEquals(ad.getCommand(), ConfigConst.COMMAND_ON)
		self.assertEquals(ad.getStateData(), self.DEFAULT_STATE_DATA)
		self.assertEquals(ad.getValue(), self.DEFAULT_VALUE)

	def testFullUpdate(self):
		ad = ActuatorData()
		ad2 = self._createTestActuatorData()
		
		ad.updateData(ad2)
		
		self.assertEquals(ad.getCommand(), ConfigConst.COMMAND_ON)
		self.assertEquals(ad.getStateData(), self.DEFAULT_STATE_DATA)
		self.assertEquals(ad.getValue(), self.DEFAULT_VALUE)
		
	def _createTestActuatorData(self):
		ad = ActuatorData()
		
		ad.setName(self.DEFAULT_NAME)
		#ad.setCommand(ConfigConst.COMMAND_ON)
		ad.setStateData(self.DEFAULT_STATE_DATA)
		ad.setValue(self.DEFAULT_VALUE)
		
		logging.info("Actuator data as string: " + str(ad))
		
		return ad


if __name__ == "__main__":
	unittest.main()
	
```

Below is the code for ActuatorData.py: 
```
#####
# 
# This class is part of the Programming the Internet of Things project.
# 
# It is provided as a simple shell to guide the student and assist with
# implementation for the Programming the Internet of Things exercises,
# and designed to be modified by the student as needed.
#

import programmingtheiot.common.ConfigConst as ConfigConst

from programmingtheiot.data.BaseIotData import BaseIotData
from pip._internal import self_outdated_check


class ActuatorData(BaseIotData):
	"""
	Shell representation of class for student implementation.
	
	"""

	def __init__(self, typeID: int=ConfigConst.DEFAULT_ACTUATOR_TYPE, 
				name=ConfigConst.NOT_SET, d=None):
		super(ActuatorData, self).__init__(name=name, typeID=typeID, d=d)
		self.command = ConfigConst.COMMAND_ON 
		self.value = ConfigConst.DEFAULT_VAL 
		self.stateData = ""
		
	
	def getCommand(self) -> int:
		return self.command
	
	def getStateData(self) -> str:
		return self.stateData
	
	def getValue(self) -> float:
		return self.value

	
	def isResponseFlagEnabled(self) -> bool:
		return False
	
	def setCommand(self, command: int):
		self.updateTimeStamp() 
		self.command = command
	
	def setAsResponse(self):
		pass
		
	def setStateData(self, stateData: str):
		self.updateTimeStamp() 
		self.stateData = stateData
	
	def setValue(self, val: float):
		self.updateTimeStamp() 
		self.value = val
		
	def _handleUpdateData(self, data):
		if data and isinstance(data, ActuatorData): 
			self.value = data.getValue()
			self.command = data.getCommand()	
			self.stateData = data.getStateData()	
				

```

**Comment by MAbuShattal** [comment]
It only works if I change the following value in the two files: ActuatorData.pt and ActuatorDataTest.py to ConfigConst.DEFAULT_COMMAND instead of self.command = ConfigConst.COMMAND_ON
This is different from what is explained in the Book code listing and the action list above. It should work for any type of COMMAND, default or not. 

Any thoughts on this?

```
Finding files... done.
Importing test modules ... done.

2021-12-14 11:23:12,490:ActuatorDataTest:INFO:Testing ActuatorData class...
2021-12-14 11:23:12,491:ConfigUtil:INFO:Loading config: ../../../../../../../config/PiotConfig.props
2021-12-14 11:23:12,491:ConfigUtil:DEBUG:Config: ['Mqtt.GatewayService', 'Coap.GatewayService', 'ConstrainedDevice']
2021-12-14 11:23:12,491:ConfigUtil:INFO:Created instance of ConfigUtil: <programmingtheiot.common.ConfigUtil.ConfigUtil object at 0x7f8e20e75a60>
2021-12-14 11:23:12,491:ActuatorDataTest:INFO:Actuator data as string: name=Not Set,typeID=0,timeStamp=2021-12-14T16:23:12.490310+00:00,statusCode=0,hasError=False,locationID=constraineddevice001,elevation=0.0,latitude=0.0,longitude=0.0
2021-12-14 11:23:12,491:ActuatorDataTest:INFO:Actuator data as string: name=ActuatorDataFooBar,typeID=0,timeStamp=2021-12-14T16:23:12.491844+00:00,statusCode=0,hasError=False,locationID=constraineddevice001,elevation=0.0,latitude=0.0,longitude=0.0
2021-12-14 11:23:12,492:ActuatorDataTest:INFO:Actuator data as string: name=ActuatorDataFooBar,typeID=0,timeStamp=2021-12-14T16:23:12.492772+00:00,statusCode=0,hasError=False,locationID=constraineddevice001,elevation=0.0,latitude=0.0,longitude=0.0
----------------------------------------------------------------------
Ran 3 tests in 0.004s

OK
```

**Comment by labbenchstudios** [comment]
Thanks for the feedback and pointing out the discrepancy. If I find an error, I'll be sure to update the errata page for the book shortly, and re-check the implementation in the code base to ensure consistency.

I'll edit this response or add a new comment after verification and - if needed - updating the instructions. Thanks again for providing your inputs!

**Comment by labbenchstudios** [comment]
I re-implemented the exercises above, and was not able to reproduce the issue with `AcutatorData`; however, the `SystemPerformanceData` instructions are missing some content here and in the book.

**SystemPerformanceData testing notes**

The `SystemPerformanceDataTest` expects that THREE variables (and their accessor functions) are set internally: `cpuUtil`, `memUtil`, and `diskUtil`; however, the instructions within the book (and originally contained above) only specify TWO: `cpuUtil` and `memUtil`.

UPDATE: After further review, to keep consistency between the CDA and GDA, I'll update the unit tests described below to remove references to `diskUtil` for `SystemPerformanceData`. Updates to the code base forthcoming.

For the short term, you can simply comment out the `diskUtil` comparison code in the four unit test functions: `testDefaultValues()`, `testParameterUpdates()`, `testFullUpdate()`, and `_createTestSystemPerformanceData()`. However, please note that the `SystemPerformanceData` sample JSON included within `DataUtilTest` also expects `diskUtil` to be set.

**ActuatorData testing notes**

The `ActuatorDataTest` currently includes only three unit test functions: `testDefaultValues()`, `testParameterValues()`, and `testFullUpdate()`.

The first unit test checks if the command is `ConfigConst.DEFAULT_COMMAND` (which is also specified in the book implementation [p. 87] and in the instructions above [see note below]), while the second and third unit tests create their own instance of `ActuatorData` via a call to `_createTestActuatorData()`, setting the command to `ConfigConst.COMMAND_ON`. Both unit tests then expect the command value will be set accordingly in their own comparison logic.

You can certainly change this in your own environment - or even add more commands if you'd like; however, you would need to either update the unit test logic accordingly, or add your own tests. I've generally found it easier to just add new unit test classes with custom unit tests to meet the needs of your own implementation, but it's up to you.

-----

UPDATE: Code in 'python-components' repository now updated: SystemPerformanceDataTest.py and DataUtilTest.py (part 02 unit tests). See [GitHub commit](https://github.com/programming-the-iot/python-components/commit/c6bdb54e4df7183e19f74122de3254f3841f7edc) for details.

**Comment by npiacen** [comment]
Having some hangup around assertEquals in the test files, although updating to assertEqual seems to fix.

Looks like assertEquals is gone from the unittest documentation. See below.

https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertEqual

**Comment by labbenchstudios** [comment]
Thanks for the comment. I'll look through the test cases and see where any updates may be necessary. Much appreciated!

**Comment by labbenchstudios** [comment]
Just updated 'python-components' - changed remaining 'assertEquals' calls in unittest test cases to 'assertEqual'.

**Comment by npiacen** [comment]
Another question (in regards to Card CDA-06-004).


   - Make sure your ConfigConst.DEFAULT_CONFIG_FILE_NAME is set properly.


The default location is shown inside of ConfigConst.py is:
DEFAULT_CONFIG_FILE_NAME = '../../../../../../../config/PiotConfig.props'

With this setting, the MQTTClientConnectorTest.py unit test is working
properly. However the CDA app shows this message and does not display the
proper
[image: Screen Shot 2024-02-17 at 10.40.24 PM.png]

ithWhen the defauly config file name is changed to:
DEFAULT_CONFIG_FILE_NAME = './config/PiotConfig.props'

The unit test fails but the CDA app running from the command line seems to
be functioning (although my output is slightly different).

See below:
[image: Screen Shot 2024-02-17 at 10.44.52 PM.png]

When I make the location the following (which is the actual  location of
the .props file):
DEFAULT_CONFIG_FILE_NAME = '~/programmingTheIot/python-components/config
/PiotConfig.props'
Neither the unit test or the CDA app running in the command line work!

Any help would be appreciated!

**Comment by labbenchstudios** [comment]
Glad to help - thanks for the query. In Chapter 1, section 'Application Configuration' of Programming the IoT (https://learning.oreilly.com/library/view/programming-the-internet/9781492081401/ch01.html), I suggest setting ```DEFAULT_CONFIG_FILE_NAME``` in ```ConfigConst.py``` to the absolute path for PiotConfig.props.

This change should help alleviate the loading idiosyncrasies between the test classes and the application for the CDA. In the GDA, the relative path (e.g., ./config/PiotConfig.props) should be sufficient for both testing and application execution.

I'll also update the instructions here to reflect this.

**Comment by npiacen** [comment]
Hello,

Thanks for the reply!

It was a matter of spelling out my entire absolute path and not using the ~
shortcut for home.

Very much enjoying this development.  I plan to put this on an actual
raspberry pi once it's all done.

As it relates to that, when deploying the CDA on an actual device, is the
idea to have a full RPi OS on the device and have the CDA app running
through the python installation on the pi?

Thanks,

Nick

**Comment by labbenchstudios** [comment]
Thanks for following up. Glad to hear you're enjoying the development process for Programming the IoT!

I've deployed my solutions for the CDA and GDA on separate Raspberry Pi devices, and currently run them on a few devices - ranging from Raspberry Pi 0w (CDA) to Raspberry Pi 4 (GDA). All devices are currently running Raspbian, although I've run both apps on Ubuntu and macOS as well.

Hope this helps - all the best with your development and testing.
